LOCK TABLES `pays` WRITE;
SET FOREIGN_KEY_CHECKS = 0;
truncate table pays;
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (1,'Aruba (Ile d\')','ABW');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (2,'Angola','AGO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (3,'Anguilla (Ile d\')','AIA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (4,'Albanie','ALB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (5,'Aland (Iles d\')','ALD');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (6,'Antilles Néerlandaises','ANT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (7,'Emirats Arabes Unis','ARE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (8,'Argentine','ARG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (9,'Kerguelen (Iles)','ATF');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (10,'Antigua et Barbuda','ATG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (11,'Australie','AUS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (12,'Autriche','AUT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (13,'Azerbaidjan','AZE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (14,'Belgique','BEL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (15,'Benin','BEN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (16,'Bangladesh','BGO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (17,'Bulgarie','BGR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (18,'Bahrein','BHR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (19,'Bahamas','BHS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (20,'Belize','BLZ');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (21,'Bermudes (Iles)','BMU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (22,'Bolivie','BOL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (23,'Brésil','BRA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (24,'Barbade (Ile de La)','BRB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (25,'Brunei','BRN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (26,'Canada','CAN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (27,'Suisse','CHE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (28,'Chili','CHL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (29,'Chine','CHN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (30,'Côte d\'Ivoire','CIV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (31,'Cameroun','CMR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (32,'Canaries (Iles)','CNI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (33,'Congo (Rép. Dem. du)','COD');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (34,'Congo','COG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (35,'Cook (Iles)','COK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (36,'Colombie','COL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (37,'Comores (Iles des)','COM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (38,'Cap Vert (Iles du)','CPV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (39,'Costa Rica','CRI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (40,'Cuba','CUB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (41,'Curaçao','CUR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (42,'Cayman (Iles)','CYM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (43,'Chypre','CYP');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (44,'Tchèque (République)','CZE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (45,'Allemagne','DEU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (46,'Djibouti','DJI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (47,'Dominique','DMA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (48,'Danemark','DNK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (49,'Dominicaine (République)','DOM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (50,'Algérie','DZA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (51,'Equateur','ECU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (52,'Egypte','EGY');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (53,'Erythrée','ERI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (54,'Espagne','ESP');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (55,'Estonie','EST');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (56,'Ethiopie','ETH');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (57,'Finlande','FIN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (58,'Fiji (Iles)','FJI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (59,'Falkland (Iles)','FLK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (60,'France','FRA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (61,'Feroe (Iles)','FRO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (62,'Micronésie','FSM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (63,'Gabon','GAB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (64,'Royaume-Uni','GBR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (65,'Georgie','GEO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (66,'Ghana','GHA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (67,'Gibraltar','GIB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (68,'Guinée','GIN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (69,'Guadeloupe','GLP');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (70,'Gambie','GMB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (71,'Guinée-Bissau','GNB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (72,'Guinée Equatoriale','GNQ');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (73,'Grèce','GRC');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (74,'Grenade','GRD');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (75,'Groenland','GRL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (76,'Guatemala','GTM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (77,'Guam','GUM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (78,'Honduras','HND');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (79,'Croatie','HRV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (80,'Haiti','HTI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (81,'Hongrie','HUN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (82,'Indonésie','IDN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (83,'Inde','IND');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (84,'Ile de Man','IOM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (85,'Irlande (Rép. d\')','IRL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (86,'Iran','IRN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (87,'Iraq','IRQ');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (88,'Iceland','ISL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (89,'Israël','ISR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (90,'Italie','ITA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (91,'Jamaïque','JAM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (92,'Jordanie','JOR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (93,'Japon','JPN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (94,'Kenya','KEN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (95,'Cambodge','KHM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (96,'Kiribati','KIR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (97,'Corée du Sud','KOR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (98,'Koweit','KWT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (99,'Kazakhstan','KZA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (100,'Laos','LAO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (101,'Liban','LBN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (102,'Liberia','LBR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (103,'Libye','LBY');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (104,'Sainte Lucie','LCA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (105,'Sri Lanka','LKA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (106,'Lituanie','LTU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (107,'Luxembourg','LUX');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (108,'Lettonie','LVA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (109,'Maroc','MAR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (110,'Monaco','MCO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (111,'Madagascar','MDG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (112,'Maldives (Iles)','MDV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (113,'Mexique','MEX');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (114,'Marshall (Iles)','MHL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (115,'Malte ','MLT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (116,'Myanmar','MMR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (117,'Mozambique','MOZ');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (118,'Mauritanie','MRT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (119,'Montenegro','MTG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (120,'Maurice (Ile)','MUS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (121,'Malaisie','MYS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (122,'Namibie','NAM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (123,'Nouvelle-Calédonie','NCL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (124,'Nigéria','NGA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (125,'Nicaragua','NIC');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (126,'Norvège (Reg. Intern.)','NIS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (127,'Pays-Bas','NLD');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (128,'Norvège','NOR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (129,'Nauru (Rép. de)','NRU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (130,'Nouvelle-Zélande','NZL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (131,'Oman','OMN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (132,'Pakistan','PAK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (133,'Panama','PAN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (134,'Pérou','PER');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (135,'Philippines','PHL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (136,'Madère','PMD');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (137,'Papouasie-Nlle Guinée','PNG');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (138,'Pologne','POL');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (139,'Porto Rico','PRI');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (140,'Corée du Nord','PRK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (141,'Portugal','PRT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (142,'Paraguay','PRY');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (143,'Polynésie Française','PYF');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (144,'Qatar','QAT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (145,'Réunion (Ile de La)','REU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (146,'Roumanie','ROM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (147,'Russie (Fédér. de)','RUS');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (148,'Arabie Saoudite (Roy. d\')','SAU');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (149,'Soudan','SDN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (150,'Sénégal','SEN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (151,'Singapour','SGP');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (152,'Salomon (Iles)','SLB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (153,'Sierra Leone','SLE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (154,'Salvador','SLV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (155,'Somalie','SOM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (156,'St Pierre et Miquelon','SPM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (157,'Sao Tome & Principe','STP');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (158,'Suriname','SUR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (159,'Slovaquie','SVK');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (160,'Slovénie','SVN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (161,'Suède','SWE');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (162,'Seychelles','SYC');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (163,'Syrie','SYR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (164,'Tahiti','TAH');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (165,'Togo','TGO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (166,'Thaïlande','THA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (167,'Turkménistan','TKM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (168,'Tonga','TON');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (169,'Trinité et Tobago','TTO');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (170,'Tunisie','TUN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (171,'Turquie','TUR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (172,'Tuvalu','TUV');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (173,'Taiwan','TWN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (174,'Tanzanie','TZA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (175,'Ouganda','UGA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (176,'Ukraine','UKR');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (177,'Uruguay','URY');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (178,'Etats-Unis','USA');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (179,'St Vincent et Grenadines','VCT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (180,'Venezuela','VEN');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (181,'Vierges (Iles)','VGB');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (182,'Vietnam','VNM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (183,'Vanuatu','VUT');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (184,'Samoa (Iles)','WSM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (185,'Yemen','YEM');
INSERT INTO `pays` (`id`, `nom`, `indicatif`) VALUES (186,'Afrique du Sud','ZAF');
SET FOREIGN_KEY_CHECKS = 1;
UNLOCK TABLES;